[package]
name = "actuate-macros"
description = "Macros for Actuate"
version = "0.1.6"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/actuate-rs/actuate"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.37"
syn = { version = "2.0.87", features = ["full"] }
